import React from 'react'

const TermsCondition = () => {
  return (
    <>
    <div className='bg-white relative z-[2] py-16 md:pt-[116px] md:pb-[163px] px-4'>
        <div className='max-w-6xl 2xl:max-w-[1440px] mx-auto'>

            <h1 className='text-black mb-[50px] md:mb-[77px] text-[32px] md:text-[40px] leading-[47px] font-bold'>Terms and Conditions</h1>
           
           
            <p className='text-[16px] md:text-[20px] block leading-[28px] md:leading-[32px]' >
            Our app, ``School Hack,`` is intended for use as an educational tool to assist students with their schoolwork.
<br />
<br />
By using our app, you agree to use it only for lawful purposes and in compliance with all applicable laws and regulations.
<br />
<br />
You agree to not use our app to engage in any activity that constitutes academic dishonesty or plagiarism.
<br />
<br />
Our app generates text based on the prompts given to it, but it is your responsibility to use the generated text responsibly and to ensure that it is properly cited and referenced.
<br />
<br />
Our app is not a substitute for your own work and you should always use your own judgment and critical thinking skills when using the app.
<br />
<br />
You agree to not share or distribute any of the content generated by our app without proper attribution.We are not liable for any damage or loss caused by your use of our app.
<br />
<br />
We reserve the right to terminate or suspend your access to our app at any time if we suspect that you are using it for any illegal or prohibited activities.
<br />
<br />
We may update these terms and conditions from time to time, and your continued use of our app will constitute your acceptance of any such changes.
            </p>
            </div>
        </div>
</> 
  )
}

export default TermsCondition